import dotenv from "dotenv";
dotenv.config();
import { Generation } from "@arkology-studio/ontothesia-types/generation";
export const generations: Generation[] = [
  {
    id: "generation_129546999",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "The River of Life",\n        ARTEFACT_TEXT: "Hail to thee, O Nile! Who manifests thyself over this land, and comes to give life to Egypt!...Watering the orchards created by Re, to cause all the cattle to live, you give the earth to drink, inexhaustible one!",\n        CONTEXT: "A grand depiction of the Nile River, flowing through ancient Egypt, surrounded by lush vegetation and farmers working on the fertile banks.",\n        VISUALISATION_GUIDE: "A golden sunrise over the Nile, where the river winds through a verdant landscape. Farmers and animals thrive along its banks, with ancient Egyptian temples and pyramids in the background. The water sparkles with life, reflecting the divine essence of Re."',
    image_url: "/1741012698766.png",
    artefact: "1",
    scene: "1",
  },
  {
    id: "generation_129547025",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "The Sage’s Counsel",\n        ARTEFACT_TEXT: "Be not proud because thou art learned; but discourse with the ignorant man, as with the sage. For no limit can be set to skill, neither is there any craftsman that possesseth full advantages. Fair speech is more rare than the emerald that is found by slave-maidens on the pebbles.",\n        CONTEXT: "A serene setting in an ancient Egyptian temple courtyard, where the aged sage Ptahhotep imparts wisdom to a gathering of scribes, artisans, and common folk. The warm glow of oil lamps flickers against the hieroglyph-covered walls.",\n        VISUALISATION_GUIDE: "An elder Egyptian vizier, draped in fine linen, sits upon a stone bench, gesturing with grace as he speaks to an attentive circle of listeners—scribes with papyrus scrolls, artisans with calloused hands, and a humble laborer leaning in with curiosity. The sun casts long shadows across the temple courtyard, illuminating inscriptions that echo the wisdom of past generations. Nearby, a young scribe carefully etches the sage’s words onto a fresh scroll, preserving the timeless lessons of humility and knowledge."',
    image_url: "/1741012703451.png",
    artefact: "2",
    scene: "2",
  },
  {
    id: "generation_129547040",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "The Radiance of Aten",\n        ARTEFACT_TEXT: "O One God, like whom there is no other! Thou didst create the earth by thy heart…men and women, cattle, beasts of every kind…Thou settest every person in his place, thou providest their daily food…their tongues are different in speech, [and] likewise their skins in colour.",\n        CONTEXT: "A grand scene set in the city of Akhetaten (modern Amarna), where Pharaoh Akhenaten and Queen Nefertiti stand beneath the sun disk Aten, its rays ending in hands bestowing life upon the people.",\n        VISUALISATION_GUIDE: "The golden sun shines high in the sky, its beams stretching down like outstretched hands over a vast temple courtyard. Akhenaten, clad in flowing white linen, raises his arms in devotion before a towering altar, while priests and devotees kneel in reverence. Farmers tend their crops by the banks of the Nile, artisans chisel hymns into stone, and distant traders arrive from foreign lands, their skin tones varied, reflecting the unity of humanity under the sun god’s divine light."',
    image_url: "/1741012707467.png",
    artefact: "3",
    scene: "3",
  },
  {
    id: "generation_129547010",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "The Compassion of a Conqueror",\n        ARTEFACT_TEXT: "When he saw that they [the horses] were starved, he said: \'As I live, as Re loves me…how much more painful it is in my heart that my horses have been starved than any other crime that you have committed. …If only another had done it to me, whom I did not know!\'",\n        CONTEXT: "A dramatic moment in the court of Piye, the Kushite king, as he confronts defeated Egyptian rulers. His fury is not for their disloyalty, but for the mistreatment of his noble warhorses.",\n        VISUALISATION_GUIDE: "In the dimly lit hall of Piye’s court, trembling governors bow before the mighty Kushite king. His voice thunders not with anger at their rebellion, but with sorrow for his neglected warhorses, standing frail and mistreated beside him. The firelight flickers across the intricate carvings of the Victory Stele, depicting Piye’s conquests. His warriors stand solemnly, their hands resting on their swords, while stable attendants rush to bring food and water to the starving animals."',
    image_url: "/1741012701821.png",
    artefact: "4",
    scene: "4",
  },
  {
    id: "generation_129546997",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "The Queen’s Wisdom",\n        ARTEFACT_TEXT: "And the Queen said unto them, \'Hearken, O ye who are my people, and give ear to my words. For I desire wisdom and my heart seeketh to find understanding. I am smitten with the love of wisdom, and I am constrained by the cords of understanding; for wisdom is far better than treasure of gold and silver, and wisdom is the best of everything that hath been created on the earth.\'",\n        CONTEXT: "Queen Makeda of Sheba stands before her people in the great palace of Aksum, addressing them with words of wisdom as they listen in awe.",\n        VISUALISATION_GUIDE: "Under the vast stone pillars of Aksum, Queen Makeda, draped in regal robes of gold and indigo, stands upon a raised dais, her voice strong and clear. The gathered nobles and scholars hang onto every word as she extols the virtues of wisdom over wealth. Sunlight filters through the palace’s grand openings, illuminating the rich tapestries and delicate incense curling into the air. In the distance, traders and scribes bustle through the streets, their scrolls and wares reflecting the knowledge and prosperity of the kingdom."',
    image_url: "/1741012700398.png",
    artefact: "5",
    scene: "5",
  },
  {
    id: "generation_129547020",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "The Birth of Mountains",\n        ARTEFACT_TEXT: "Because the earth was just flat with no features, Wak asked man to make his own coffin, and when man did this, Wak shut him up in it and pushed it into the ground. For seven years he made fire rain down and the mountains were formed. Then Wak unearthed the coffin and man sprang forth, alive.",\n        CONTEXT: "A cosmic event unfolds as Wak shapes the earth through fire and transformation, burying and resurrecting the first man from the depths of the land.",\n        VISUALISATION_GUIDE: "A vast, barren landscape stretches endlessly under a darkened sky. Suddenly, fiery rain descends, striking the ground with force, igniting molten rivers and pushing the earth into towering mountains. At the heart of this fiery transformation, a single coffin lies buried deep. As the storm subsides, the ground trembles, and the coffin bursts open—revealing the first man, emerging into a world now rich with peaks and valleys, shaped by Wak’s divine hand."',
    image_url: "/1741012703318.png",
    artefact: "6",
    scene: "6",
  },
  {
    id: "generation_129547018",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "A Mother\'s Final Lesson",\n        ARTEFACT_TEXT: "Come close to me my daughter, and listen to my advice; young though you are, perhaps you will pay attention to it. I have been ill for a whole year and have not had an opportunity to talk properly to you.",\n        CONTEXT: "In a quiet coastal home, a mother on her deathbed imparts her final wisdom to her young daughter, sharing lessons of life, love, and resilience.",\n        VISUALISATION_GUIDE: "A dimly lit room near the ocean, where the salty breeze carries the scent of jasmine. An elder Swahili woman, wrapped in delicate fabrics, reclines on a woven mat, her frail hands resting on her daughter\'s. The young girl, dressed in traditional Swahili attire, listens intently as her mother speaks, her voice filled with warmth and urgency. Outside, the sound of gentle waves and distant dhows sailing on the horizon echoes the passage of time, while a flickering oil lamp illuminates the mother’s face, casting long shadows on the walls inscribed with Swahili poetry."',
    image_url: "/1741012701528.png",
    artefact: "7",
    scene: "7",
  },
  {
    id: "generation_129547016",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "The Awakening of Life",\n        ARTEFACT_TEXT: "The first man and woman had no children for a long time. They did not know the secret of procreation and tried to have union in various ways without success. One day the man saw the woman climbing a tree and noticed her private parts, and so that night he sought union with her again. She refused at first, saying that he had only seen an ulcer, but later she gave in.",\n        CONTEXT: "The first man and woman, oblivious to the ways of procreation, come to a moment of realization in the quiet wilderness, shaping the destiny of future generations.",\n        VISUALISATION_GUIDE: "In a lush, ancient forest, the first man sits by a riverbank, deep in thought. His companion climbs a towering tree nearby, her silhouette framed against the golden sunset. As he glances upward, understanding dawns upon him—a revelation that will forever alter their existence. That night, under the starlit sky, he approaches her with newfound wisdom. The forest hums with the sounds of nocturnal life, bearing witness to the first union that will bring forth the lineage of humankind."',
    image_url: "/1741012700685.png",
    artefact: "8",
    scene: "8",
  },
  {
    id: "generation_129547003",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "The Birth of Ife",\n        ARTEFACT_TEXT: "In the beginning, there was only the sky above, water and marshland below. The chief god Olorun ruled the sky, and the goddess Olokun ruled what was below. Obatala, another god, sought permission from Olorun to create dry land for living creatures. …He poured sand from a snail\'s shell and released a white hen. The hen scattered the sand, creating dry land – the larger piles became hills and the smaller piles valleys. Obatala jumped to a hill and named the place Ife.",\n        CONTEXT: "The divine realm descends upon the waters as Obatala crafts the land, shaping the world from a mere shell of sand and the gentle fluttering of a hen’s wings.",\n        VISUALISATION_GUIDE: "A boundless ocean stretches in every direction, its surface rippling beneath a sky where gods dwell. Obatala, draped in celestial robes, stands upon the clouds, holding a snail shell filled with divine sand. With a graceful hand, he releases its contents, watching as a white hen flutters down, scattering the grains across the water’s surface. Hills rise, valleys take shape, and the first land emerges—golden in the morning light. Obatala leaps down, his feet touching the sacred ground, naming it Ife, the cradle of the Yoruba people."',
    image_url: "/1741012700523.png",
    artefact: "9",
    scene: "9",
  },
  {
    id: "generation_129547027",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "The Python’s Gift",\n        ARTEFACT_TEXT: "Long ago a man and a woman came down from heaven, while another man and woman came out of the ground. The \'Lord of the Heavens\' also sent an African python…In the beginning men and women had no children; they had no desire for one another and did not know the process of procreation. It was the Python who taught them.",\n        CONTEXT: "Two couples—one from the heavens, one from the earth—stand at the dawn of humanity, learning the secret of life from a sacred python.",\n        VISUALISATION_GUIDE: "A twilight-lit clearing in the heart of a dense rainforest. Two men and two women, each bearing the markings of their divine origins, stand in quiet curiosity. From the shadows, an immense African python glides forth, its golden eyes glowing with ancient wisdom. It coils gently around them, whispering secrets in the language of nature. The humans listen, their expressions shifting from confusion to understanding. In that sacred moment, under the watchful gaze of the moon, they receive the knowledge that will ensure the continuation of their lineage."',
    image_url: "/1741012703420.png",
    artefact: "10",
    scene: "10",
  },
  {
    id: "generation_129547004",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "Defying the Creator",\n        ARTEFACT_TEXT: "The creator, Abassi, created two humans and then decided not to allow them to live on earth. His wife, Atai, persuaded him to let the people live on earth. In order to control the humans, Abassi insisted that they eat all their meals with him (so they would not grow or hunt food). He also forbade them to have children. But soon the woman began growing food on the earth and stopped showing up to eat with Abassi…",\n        CONTEXT: "The first humans, created by Abassi, live under his strict rule, but the woman’s quiet defiance begins to change the fate of humankind.",\n        VISUALISATION_GUIDE: "A celestial palace hovers above the clouds, where Abassi and Atai watch over the first humans below. A lush but untouched land stretches beneath the sky, bathed in golden light. The man and woman sit by Abassi’s table, eating as he commands, but something stirs within them. One day, the woman kneels in the dark earth, pressing seeds into the soil. Green shoots burst forth, defying the laws set by their creator. The sky trembles with Abassi’s displeasure, but the woman continues, her hands steady as she claims the earth as her own."',
    image_url: "/1741012699805.png",
    artefact: "11",
    scene: "11",
  },
  {
    id: "generation_129547009",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "The Gods Create a Ruler",\n        ARTEFACT_TEXT: "In the beginning there was nothing but Nzame. This god is really three: Nzame, Mebere, and Nkwa. It was the Nzame aspect that created the universe and the earth, and brought life to it. While the three parts of Nzame were admiring this creation, it was decided to create a ruler for the earth. So was created the elephant, the leopard, and the monkey, but it was decided that something better had to be created.",\n        CONTEXT: "Nzame and his divine aspects shape the universe, admiring its beauty before deciding that a ruler is needed to govern the earth.",\n        VISUALISATION_GUIDE: "A vast, swirling cosmos fills the sky, where three luminous beings—Nzame, Mebere, and Nkwa—converse in divine harmony. Below, the earth takes shape, its lands and rivers unfolding like a grand tapestry. The gods first create a mighty elephant, a swift leopard, and a clever monkey, watching as they roam the newborn world. Yet, dissatisfaction lingers in their divine hearts. The three aspects of Nzame turn to one another, their forms shimmering with celestial light, and agree that something greater is needed—a being to truly rule over the world they have crafted."',
    image_url: "/1741012699730.png",
    artefact: "12",
    scene: "12",
  },
  {
    id: "generation_129547005",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "The Golden City of Knowledge",\n        ARTEFACT_TEXT: "There are in Timbuktu numerous judges, teachers and priests, all properly appointed by the king. He greatly honors learning. Many hand-written books imported from Barbary are also sold – there is more profit made from this commerce than from all other merchandise. …Instead of coined money, pure gold nuggets are used, and for small purchases, cowrie shells.",\n        CONTEXT: "A bustling scene in the heart of Timbuktu, where scholars, merchants, and travelers gather in the famous marketplaces and universities.",\n        VISUALISATION_GUIDE: "The sun rises over the grand city of Timbuktu, its towering mud-brick mosques casting long shadows over the sand-covered streets. In the marketplace, merchants display goods—rolls of fine textiles, pots of fragrant spices, and stacks of handwritten manuscripts brought from distant lands. A scholar, dressed in flowing indigo robes, examines a rare book with careful hands, while traders barter using gold nuggets and cowrie shells. Nearby, young students gather outside the great Sankore University, eagerly listening to their teacher as they prepare to record his wisdom onto fresh parchment."',
    image_url: "/1741012701437.png",
    artefact: "13",
    scene: "13",
  },
  {
    id: "generation_129547030",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "Bumba\'s Birth of the Cosmos",\n        ARTEFACT_TEXT: "In the beginning, in the dark, there was nothing but water. And Bumba was alone. One day Bumba was in terrible pain. He retched and strained and vomited up the sun. After that, light spread over everything. The heat of the sun dried up the water until black sandbanks and reefs began to show. But there were no living things yet. Then Bumba vomited up the moon and then the stars, and after that the night had its light also.",\n        CONTEXT: "In the silent, endless waters of the beginning, the god Bumba writhes in pain, his suffering birthing the very elements of existence.",\n        VISUALISATION_GUIDE: "A vast, endless ocean stretches into darkness, the only sound the slow rippling of waves. Suddenly, a great luminous figure—Bumba—emerges, his body heaving in agony. With an earth-shaking cry, he vomits forth the sun, which explodes into brilliance, casting golden light across the once-dark waters. The heat rises, the waves recede, and land emerges—black sandbanks forming islands and continents. In the growing light, Bumba strains once more, releasing the moon and stars into the heavens, their silver glow bringing peace to the night. The world, once empty, now holds the promise of life."',
    image_url: "/1741012703915.png",
    artefact: "14",
    scene: "14",
  },
  {
    id: "generation_129547017",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "Modimo, Keeper of Balance",\n        ARTEFACT_TEXT: "Modimo was the creator. He distributed good things, appearing in the east and belonging to the element water. At the same time he was a destroyer, a terrifying force responsible for drought, hail, cyclones and earthquakes. When these things happened, he appeared in the west and was part of the element fire. Modimo was also sky and light, earth and root – he was unique and singular, with no ancestors, no past or future, pervading the whole of creation.",\n        CONTEXT: "A divine representation of Modimo as both creator and destroyer, shaping the world through water and fire, embodying all elements of existence.",\n        VISUALISATION_GUIDE: "A vast celestial figure looms over the world, half bathed in golden sunlight and half shrouded in a stormy inferno. From the east, gentle rains fall, nourishing the land, while in the west, raging fires consume the earth, cracking the soil and summoning mighty tempests. Beneath this divine force, rivers carve valleys, mountains rise from the ground, and life flourishes and perishes in an endless cycle. Modimo, neither past nor future, watches over all, his eyes reflecting the endless expanse of creation."',
    image_url: "/1741012702165.png",
    artefact: "15",
    scene: "15",
  },
  {
    id: "generation_129547036",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "The Dance of the Baboons",\n        ARTEFACT_TEXT: "One day the mischievous little hairy men (baboons) met Cagn\'s son, Cogaz. \'Your father thinks he is so clever, making bows to kill us. We will kill you instead,\' they jeered. So they killed poor Cogaz, then tied him up in the top of a tree and danced around it singing. Cagn awoke and sensed something wrong. Using a magic charm, he discovered what happened. He found the dancing baboon-men and ordered them to sing the same song. As they danced, he went behind each one and drove a piece of grass rope into each one\'s backside with a magical crack. They all bounded off to the mountains, barking and leaping with their hairy tails sticking up behind – thus they became baboons forever. (Cagn then magically revived his son.)",\n        CONTEXT: "A mischievous and magical tale of Cagn\'s son, Cogaz, and his transformation of the laughing baboon-men.",\n        VISUALISATION_GUIDE: "In the golden dusk of the savanna, a group of hairy, mischievous baboon-men circle a tree, their laughter echoing through the air as they celebrate their misdeed. Atop the tree, the lifeless form of Cogaz hangs, bound by their crude knots. Suddenly, a wind stirs. Cagn steps from the shadows, his eyes glowing with ancestral power. As he commands them to dance their own song, he moves unseen, pressing enchanted grass ropes against their backs. One by one, their forms contort—tails sprout, limbs shorten, their voices twist into hoots and barks. With a final leap, they flee into the mountains, never to be men again. Behind Cagn, Cogaz stirs, breathing once more."',
    image_url: "/1741012705409.png",
    artefact: "16",
    scene: "16",
  },
  {
    id: "generation_129547035",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "The Mantis and the Moon",\n        ARTEFACT_TEXT: "The moon sent a Praying Mantis to man with the following message: \'As I die, and by dying bring forth life, so you shall also die, and by dying bring forth new life.\' Off went the Mantis with his message, but his legs were short and, unable to see very well, he lost his way many times.",\n        CONTEXT: "A poetic moment in which the Praying Mantis carries the message of the moon, only to falter on his journey, forever changing the fate of humankind.",\n        VISUALISATION_GUIDE: "A vast, empty desert glows under the pale light of the full moon. A tiny Praying Mantis, fragile yet determined, struggles to carry a sacred message across the endless sands. Each step is slow, hindered by the shifting dunes, his short legs trembling with effort. The moon above pulses with divine radiance, watching as the messenger loses his way again and again. In the distance, a group of early humans gather around a fire, unaware that their fate is being shaped by this small, lost traveler. As dawn approaches, the Mantis finally stops, exhausted—the message undelivered, its meaning lost to time. And so, unlike the moon that dies and returns, humans are doomed to pass on forever."',
    image_url: "/1741012705153.png",
    artefact: "17",
    scene: "17",
  },
  {
    id: "generation_129547012",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "A King’s Plea",\n        ARTEFACT_TEXT: "...our Kingdom is being lost in so many ways... This is caused by the excessive liberty given by your agents to the men and merchants who come to this kingdom. They bring goods and things which have been prohibited by us, so that many of our vassals... do not comply [with our authority], as they have these things in greater abundance than we ourselves. ...The mentioned merchants are taking every day our natives, sons of the land and sons of our noblemen and vassals, because the thieves and men of bad conscience grab them... to be sold; so great is the corruption that our country is being completely depopulated. And Your Highness should not agree with this nor accept it as being in your service...",\n        CONTEXT: "King Afonso I of Kongo, seated in his royal court, pens a desperate letter to the King of Portugal, lamenting the destruction of his kingdom through unchecked slavery and corruption.",\n        VISUALISATION_GUIDE: "In a grand but troubled court, King Afonso I sits at an ornate wooden desk, quill in hand, his face marked with grief. Around him, noblemen whisper anxiously, while outside, the sound of commotion rises—merchants from foreign lands trade stolen Kongo subjects like cattle, their faces indifferent to the suffering they cause. The King’s eyes scan his own words, the ink barely dry: a plea to the distant King of Portugal, a cry against the ruin overtaking his lands. In the distance, shadows stretch toward the horizon—empty villages, families torn apart, a once-mighty kingdom unraveling. And yet, the letter must be sent. Perhaps, even now, it is not too late."',
    image_url: "/1741012702363.png",
    artefact: "18",
    scene: "18",
  },
  {
    id: "generation_129547008",
    prompt:
      '\n        Create an image of a scene that depicts in some way the ARTEFACT_TEXT. \n        The CONTEXT should inform the depiction of the scene and the VISUALISATION GUIDE will inform how to depict the ARTEFACT_TEXT:\n\n        General Instructions:\n        The image should fade into a black background in a smokey way. No part of the representation should touch the borders.\n\n        You can be abstract but should only do so if the text gestures towards abstraction\n\n        Your goal is focus on a centeral subject with a clear forground and a background that disappears into black #000000\n\n        Do not create any text in the image.\n\n        TITLE: "The Chains of the Middle Passage",\n        ARTEFACT_TEXT: "When I looked round the ship too and saw a large furnace of copper boiling, and a multitude of black people of every description chained together, every one of their countenances expressing dejection and sorrow, I no longer doubted my fate. Quite overpowered with horror and anguish, I fell motionless on the deck and fainted.",\n        CONTEXT: "A moment of horror and despair aboard a slave ship, as Olaudah Equiano witnesses the cruel reality of his fate.",\n        VISUALISATION_GUIDE: "A dark, suffocating ship’s hold, the air thick with the scent of sweat, sickness, and fear. Shackled together, men, women, and children lie pressed against one another, their eyes hollow with exhaustion. In the flickering light of a lantern, a massive copper furnace bubbles ominously, its heat suffocating in the already cramped space. Olaudah Equiano, barely more than a boy, clutches his knees to his chest, his breath ragged. He looks around—faces of every age and kind, all bound in iron, all drowning in sorrow. Overwhelmed, he collapses onto the wooden planks, the weight of fate pressing down on him. Outside, the sea stretches endlessly, indifferent to the cries within."',
    image_url: "/1741012701328.png",
    artefact: "19",
    scene: "19",
  },
];
