export const projectInfo = [
  {
    title: "Overview",
    paragraph: `Ontothesia emerges from the confluence of *ontology* and *synesthesia*, invoking both the layered complexity of being and the sense-blurring interplay that arises when multiple forms of knowledge converge.
  
  At its core, the project grapples with how cultural, philosophical, and creative texts interrelate when freed from static categorisations. Drawing on Gilbert Simondon’s concept of transduction—the idea that new forms arise from the interactive potential of preexisting elements—it posits that cultural artefacts, once placed in meaningful conversation, can give rise to entirely novel forms of expression. Rather than isolating these artefacts in rigid, siloed structures, *Ontothesia* treats them as dynamic nodes of information that collectively shape each other’s significance.
  
  Grounded in African cultural contexts, Ontothesia also draws on Bayo Akomolafe’s call to reimagine the relationships between people, technologies, and worlds beyond conventional humanist frameworks. The project situates African epistemologies as powerful sites of knowledge-making, where oral traditions, migratory histories, and indigenous philosophies intersect. By mapping textual, visual, and performative elements into a semantic web, Ontothesia seeks to create an environment in which these various modes of being and knowing can resonate and reshape one another. In doing so, it not only archives and reanimates African cultural expressions, but also nurtures fresh ontological possibilities that challenge the impositions of colonial borders and rigid definitions of identity.
  
  At a practical level, Ontothesia unfolds as a space where audiences can traverse the cultural matrix through an immersive exhibition. Participants begin with a single artefact—a poem, a philosophical treatise, a fragment of oral history—and are guided through the semantic connections that bind it to other works across the continent. Yet the project aspires to move beyond mapping alone. In line with Simondon’s transductive logic, each artefact becomes a catalyst for generative expressions, visually morphing into haunting, dreamlike representations that merge elements from diverse sources. In this sense, Ontothesia isn’t merely about charting cultural knowledge but catalyzing new ways of envisioning the shared, yet profoundly diverse, African experience.`,
  },
  {
    title: "To Archive is to Imagine and to Imagine is to Create",
    paragraph: `Archiving is far more than a passive act of preservation; it is an intimate and animate process of encountering the past so that the future may be shaped with clarity, intentionality, and provenance. In many African traditions, the transmission of knowledge is carried through oral storytelling, embodied rituals, and collective memory rather than through written documentation alone. By acknowledging the cultural artefacts, philosophies, and material histories that have survived and evolved over centuries—despite colonisation, displacement, and imposed borders—we not only witness these rich legacies but also provide the building blocks for visionary thought. To engage in this practice is to affirm that our imaginings of tomorrow are inextricably woven from yesterday’s lived experiences. We witness through archives not to replicate the past but to illuminate its relevance in the present, thereby seeding the possibilities for new creative departures and future commitments.
  
  Yet the scope of archiving within this project is as expansive as Africa’s history itself. It includes not only indigenous texts and oral traditions but also the complex body of colonial writings and perspectives that, however troubling, remain integral to any full understanding of Africa’s historical tapestry. These voices, when situated within a decolonial ontology, become a locus of critical reflection rather than an acceptance of colonial logic. The archive thus becomes a space of conscious encounter, where the interplay of contested narratives helps break open new modes of thinking and being.
  
  In this sense, the archive is generative and creative: it constitutes a dynamic repository of ideas, narratives, and potentialities waiting to be reactivated. Each recorded detail—be it a folk tale, political manifesto, architectural blueprint, colonist poem, or piece of oral wisdom—becomes a conduit to renewed cultural expressions. By looking back as witnesses, we become architects of the future, forging new aesthetic and intellectual paths that are grounded in the resilience and imagination of those who came before us. The inherent power in archiving is thus deeply emancipatory. It enables us to tell stories on our own terms, to expand our conceptual vocabulary, and to craft futures that echo with the enduring presence of our past.`,
  },
  {
    title: "The Fraught Terrain of Archiving",
    paragraph: `In constructing any archive, we confront a deep imbalance: colonial producers of culture often commanded more power and resources, disproportionately elevating their perspectives in historical records. This disparity is further complicated by the fact that text itself can function as a colonial medium. Organizations like [Whose Knowledge?](https://whoseknowledge.org/) have underscored how dominant archives—especially those reliant on written documentation—tend to privilege Western frameworks of meaning-making. Hence, even when curatorial efforts aspire to be representative, they risk reproducing systems of hierarchy and exclusion embedded in the very format of the archive.
  
  Moreover, the technologies we use to compile, visualize, and disseminate these records can unwittingly reinforce colonial logics. Virtual platforms, digital mapping, and text-to-image generators, while powerful, are founded on epistemological assumptions that may neglect embodied traditions of storytelling and living knowledge. Many Indigenous communities across Africa have historically woven their collective memories into song, dance, ritual, and oral narratives—forms of expression that resist neat textual enclosure. As an artistic intervention, one approach could be a distributed story-collecting exercise or community-based survey, designed to capture ancestral anecdotes and embodied culture in more fluid, inclusive ways. By actively seeking out personal recollections and lived experiences, the archive transforms from a passive repository into an evolving tapestry, one that acknowledges the vulnerabilities and biases in its own methodology while striving for a more equitable and emancipatory lens on the past.`,
  },
  {
    title: "Philosophical and Theoretical Foundations",
    paragraph: `At the heart of Ontothesia is a synthesis of ideas drawn from three major thinkers: Gilbert Simondon, Bayo Akomolafe, and Ruth Wilson Gilmore. Their diverse intellectual frameworks converge in this project’s ambition to generate “hyperobjects” of knowledge—dynamic, more-than-human entities that embody cultural multiplicities while probing the limits of colonial modes of representation. Yet the decolonial aspirations of Ontothesia are approached with humility: the AI-driven systems employed here rely on corpora, languages, and technologies that evolved within colonial contexts. Rather than proposing a conclusive solution to these structural constraints, Ontothesia acknowledges the tension between its goals and the tools it must utilize, inviting continuous reflection on how new forms of knowledge production might emerge within these complexities.
  
  Gilbert Simondon’s insights on transduction and individuation provide a conceptual anchor for the project’s methodology. Simondon defines transduction as a process through which preindividual elements—such as texts, cultural artefacts, and oral histories—give rise to novel, more complex forms.`,
  },
  {
    title: "Technical Overview",
    paragraph: `The primary process of this project is the creation of cultural and semantic maps that draw out the relational coordinates of each artefact. Texts, oral histories, theoretical writings, and other cultural pieces are embedded in a high-dimensional space using machine learning models trained to discern semantic similarity. When a chosen artefact—say, a poem, a historical document, or a philosophical treatise—enters the system as a “node,” the model locates its position within a graph and links it to neighbouring nodes based on their conceptual proximity. Over multiple “hops,” this forms a network of interconnected nodes, revealing how different pieces share themes, motifs, or discursive threads across regions, periods, or intellectual traditions.`,
  },
];
